---
- name: install logstash with jenkins
  hosts: webserver
  become: yes
  remote_user: itachi
  become_user: root
  tasks:
      - name: Install logstash
        apt:
            install: logstash
            update_cache: yes
        
      - name: Run logstash
        service:
                name: logstash
                state: started 